# Generated by Django 4.2.1 on 2023-05-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzashop',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('short_description', models.CharField(max_length=100, verbose_name='Короткая информация')),
                ('img', models.ImageField(upload_to='pizza_image/', verbose_name='Изображение')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzashopapp.pizzashop', verbose_name='Владелец')),
            ],
        ),
    ]
